pipeline {
	agent any
	stages {
		stage("Ejercicio Jenkins 4") {
			steps {
				print "Juan ha cometido una infraccion."
				print "Dani no ha cometido una infraccion."
				print "Carlos no ha cometido una infraccion."
			}
		}
	}
}
